# Set strict to true to turn warnings into errors to catch warnings within CI.
strict: true
theme:
  name: windmill
  # By default, fonts are pulled from Google on the Internet. To support offline usage, this is
  # disabled.
  font: false
  palette:
    scheme: default
    primary: white
    accent: white
  icon:
    logo: material/math-integral-box
    # GitHub specific.
    repo: fontawesome/brands/github
  favicon: https://idlepig.coding.net/p/image/d/image/git/raw/master/1645453787343.jpg
  features:
    - content.code.annotate
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
markdown_extensions:
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idlepig/blog
# This is needed to allow links to work when opened from the file system.
use_directory_urls: false
plugins:
    - search
    - mermaid2
  # This plugin is used to validate URLs (including some anchors).
  # Uncomment to build the docs with this validation enabled.
  # This is commented out by default because this requires network I/O to validate URLs, so it is
  # inherently not exactly reproducible. But this plugin is none-the-less helpful at detecting
  # incorrect URLs.
#  - htmlproofer:
#      raise_error: True
site_name: idlepig
copyright: Copyright &copy; 2019-2022 idlepig
# GitHub Specific Configuration.
#repo_name: blog
repo_url: https://github.com/idlepig/blog
edit_uri: blob/main/docs/