# This GitHub Actions job will build the user guide and publish it to the
# gh-pages branch each time the master branch is updated. This branch is
# configured to be served automatically using GitHub Pages.
name: pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin==0.5.2 mkdocs-windmill==1.0.4 oss2==2.16.0
      - run: mkdocs gh-deploy --force
      - name: upload to aliyun oss
        env:
          aliyun_key: ${{ secrets.ACCESS_KEY_ID }}
          aliyun_secret: ${{ secrets.ACCESS_KEY_SECRET }}
        run: |
          mkdocs build
          python upload_to_aliyun_oss.py